agenda/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Agendamento de Horários'
admin.site.index_title = 'LavaCar - Agendamento de Horários'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('cliente.urls')),
    path('', include('funcionario.urls')),
    path('', include('produto.urls')),
    path('', include('servico.urls')),
path('', include('atendimento.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atendimento/urls.py
from django.urls import path
from .views import AtendimentoView

urlpatterns = [
    path('atendimentos', AtendimentoView.as_view(), name='atendimentos'),
]

home/urls.py
from django.urls import path
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name = 'index'),
]

atendimento/models.py
from django.db import models

# Create your models here.
class Atendimento(models.Model):
    SITUACAO_OPCOES = (
        ('A', 'Agendado'),
        ('R', 'Realizado'),
        ('C', 'Concluido')
    )
    horario = models.DateTimeField('Horário', help_text='Data e hora do atendimento')
    cliente = models.ForeignKey('cliente.Cliente', verbose_name='Cliente', help_text='Nome do cliente', on_delete=models.CASCADE)
    funcionario = models.ForeignKey('funcionario.Funcionario', verbose_name='Funcionário', help_text='Nome do Funcionario', on_delete=models.CASCADE)
    situacao = models.CharField('Situação', max_length=15, help_text='Situação do atendimento', choices=SITUACAO_OPCOES, default='A')
    servico = models.ForeignKey('servico.Servico', verbose_name='Serviço', help_text='Nome do Serviço', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Atendimento'
        verbose_name_plural = 'Atendimentos'

    def __str__(self):
        return  f'Cliente:{self.cliente} - Funcionário:{self.funcionario} - Serviço:{self.servico}'

atendimento/forms.py
from django import forms

from cliente.models import Cliente
from funcionario.models import Funcionario
from servico.models import Servico


class AtendimentoListForm(forms.Form):
    SITUACAO_OPCOES = (
        ('T', '-------------'),
        ('A', 'Agendado'),
        ('R', 'Realizado'),
        ('C', 'Cancelado')
    )

    cliente = forms.ModelChoiceField(label ='Cliente:', widget=forms.Select(
        attrs={'class': 'select is-fullwidth'}), queryset=Cliente.objects.all(), required=False)

    funcionario = forms.ModelChoiceField(label='Funcionário:', widget=forms.Select(
        attrs={'class': 'select is-fullwidth'}), queryset=Funcionario.objects.all(), required=False)

    servico = forms.ModelChoiceField(label='Serviço:', widget=forms.Select(
        attrs={'class': 'select is-fullwidth'}), queryset=Servico.objects.all(), required=False)

    situacao = forms.ChoiceField(label='Situação:', widget=forms.Select(
        attrs={'class': 'select is-fullwidth'}), choices=SITUACAO_OPCOES, required=False)

atendimento/views.py
from django.shortcuts import render
from django.views.generic import ListView

from home.utils import HtmlToPdf
from .forms import AtendimentoListForm
from .models import Atendimento


class AtendimentoView(ListView):
    model = Atendimento
    template_name = 'atendimentos.html'

    def get_context_data(self, **kwargs):
        context = super(AtendimentoView, self).get_context_data(**kwargs)

        if self.request.GET:
            form = AtendimentoListForm(self.request.GET)
        else:
            form = AtendimentoListForm()

        context['form'] = form

        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(AtendimentoView, self).get_queryset()

        if self.request.GET:
            form = AtendimentoListForm(self.request.GET)
            if form.is_valid():
                cliente = form.cleaned_data.get('cliente')
                funcionario = form.cleaned_data.get('funcionario')
                servico = form.cleaned_data.get('servico')
                situacao = form.cleaned_data.get('situacao')

                if cliente:
                    qs = qs.filter(cliente=cliente)

                if funcionario:
                    qs = qs.filter(funcionario=funcionario)

                if servico:
                    qs = qs.filter(servico=servico)

                if situacao != 'T':
                    qs = qs.filter(situacao__icontains=situacao)

        return qs

    def get(self, *args, **kwargs):
        if self.request.GET.get('imprimir') == 'pdf':
            html_pdf = HtmlToPdf(arquivo='atendimento_pdf', qs=self.get_queryset())
            return html_pdf.response
        else:
            return super(AtendimentoView, self).get(*args, **kwargs)

atendimento/templates/atendimento_pdf.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
{% block head %}
    {% include "head.html" %}
{% endblock %}

<body>
    <div class="contaimer has-text-centered">
        <h1 class="title is-size-1">Sistema de Agendamentos</h1>
    </div>
    <section class="section has-backgroud-link-light">
        {% if object_list %}
        <div style="text-align: center;"> <h1 class="subtitle is-size-4">Atendimento Cadastrados</h1>
             <div class="table">
            <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <thead>
                <tr>
                    <th class="has-text-center">Horario</th>
                    <th class="has-text-center">Cliente</th>
                    <th class="has-text-center">Funcionario</th>
                    <th class="has-text-center">Serviço</th>
                    <th class="has-text-center">Situação</th>
                </tr>
                </thead>
                <tbody>
                {% for atendimento in object_list %}
                    <tr>
                        <td>{{atendimento.horario}}</td>
                        <td>{{atendimento.cliente}}</td>
                        <td>{{atendimento.funcionario}}</td>
                        <td>{{atendimento.servico}}</td>
                        <td>{{atendimento.situacao}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
            {% else %}
            <h2> Não existem Atendimentos cadastrados!</h2>
            {% endif %}
        </div>
    </section>
</body>
</html>

atendimento/templates/atendimentos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="section has-backgroud-link-light">
    <div class="container">
        <form id="formListaAtendimentos" action="" method="GET">
            <input type="hidden" name="imprimir" id="imprimir" value="">
            <div class="field is-grouped is-flex is-align-items-center is-flex-wrap-wrap">
                <label class="label p-2 mt-2">{{ form.cliente.label }} </label>
                <div class="control is-expanded">
                   {{ form.cliente }}
                </div>

                <label class="label p-2 mt-2">{{ form.funcionario.label }} </label>
                <div class="control is-expanded">
                   {{ form.funcionario }}
                </div>
                <label class="label p-2 mt-2">{{ form.servico.label }} </label>
                <div class="control is-expanded">
                   {{ form.servico }}
                </div>
                <label class="label p-2 mt-2">{{ form.situacao.label }} </label>
                <div class="control is-expanded">
                   {{ form.situacao }}
                </div>
                 <div class="control">
                    <button type="button" class="button is-link" onclick="geraPdf('', 'formListaAtendimentos');">
                        Buscar
                    </button>
                </div>
                {% if object_list %}
                <div class="control">
                    <button type="button" class="button is-link" onclick="geraPdf('pdf', 'formListaAtendimentos');">
                        Imprimir
                    </button>
                </div>
                {% endif %}
            </div>
        </form>
        {% if object_list %}
        <div style="text-align: center"><h1 class="subtitle is-size-4">Agendamentos Cadastrados</h1></div>
        <div class="table">
            <table class="table is-table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
                <tr>
                    <th class="has-text-center">Horário</th>
                    <th class="has-text-center">Cliente</th>
                    <th class="has-text-center">Funcionário</th>
                    <th class="has-text-center">Serviço</th>
                    <th class="has-text-center">Situação</th>
                </tr>

                <tbody>
                {% for agendamento in object_list %}
                 <tr>
                     <td>{{ agendamento.horario }}</td>
                     <td>{{ agendamento.cliente }}</td>
                     <td>{{ agendamento.funcionario }}</td>
                     <td>{{ agendamento.servico }}</td>
                     <td>{{ agendamento.get_situacao_display }}</td>
                 </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
      {% else %}
          <h2> Não existe clientes cadastrados!</h2>
      {% endif %}
    </div>
    <div class="mt-3" style="text-align: center">
        <span class="step-links">
            {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current">
                <strong>{{ object_list.number }}</strong> de {{ object_list.paginator.num_pages }}
            </span>

            {% if object_list.has_next %}
                 <a href="?page={{ object_list.next_page_number }}">Próxima</a>
            {% endif %}
        </span>
    </div>
</section>
{% endblock %}